haskell-ci

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,9 +4,11 @@
 #
 # For more information, see https://github.com/haskell-CI/haskell-ci
 #
-# version: 0.3.20190815
+# version: 0.8
 #
+version: ~> 1.0
 language: c
+os: linux
 dist: xenial
 git:
   # whether to recursively clone submodules
@@ -15,6 +17,7 @@ cache:
   directories:
     - $HOME/.cabal/packages
     - $HOME/.cabal/store
+    - $HOME/.hlint
 before_cache:
   - rm -fv $CABALHOME/packages/hackage.haskell.org/build-reports.log
   # remove files that are regenerated by 'cabal update'
@@ -24,13 +27,15 @@ before_cache:
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar
   - rm -fv $CABALHOME/packages/hackage.haskell.org/01-index.tar.idx
   - rm -rfv $CABALHOME/packages/head.hackage
-matrix:
+jobs:
   include:
     - compiler: ghc-8.6.5
-      addons: {"apt":{"sources":["hvr-ghc"],"packages":["ghc-8.6.5","cabal-install-3.0"]}}
+      addons: {"apt":{"sources":[{"sourceline":"deb http://ppa.launchpad.net/hvr/ghc/ubuntu xenial main","key_url":"https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x063dab2bdc0b3f9fcebc378bff3aeacef6f88286"}],"packages":["ghc-8.6.5","cabal-install-3.0"]}}
+      os: linux
 before_install:
   - HC=$(echo "/opt/$CC/bin/ghc" | sed 's/-/\//')
   - WITHCOMPILER="-w $HC"
+  - HADDOCK=$(echo "/opt/$CC/bin/haddock" | sed 's/-/\//')
   - HCPKG="$HC-pkg"
   - unset CC
   - CABAL=/opt/ghc/bin/cabal
@@ -67,21 +72,32 @@ install:
   - HEADHACKAGE=false
   - rm -f $CABALHOME/config
   - |
-    echo "verbose: normal +nowrap +markoutput"          >> $CABALHOME/config
-    echo "remote-build-reporting: anonymous"            >> $CABALHOME/config
-    echo "write-ghc-environment-files: always"          >> $CABALHOME/config
-    echo "remote-repo-cache: $CABALHOME/packages"       >> $CABALHOME/config
-    echo "logs-dir:          $CABALHOME/logs"           >> $CABALHOME/config
-    echo "world-file:        $CABALHOME/world"          >> $CABALHOME/config
-    echo "extra-prog-path:   $CABALHOME/bin"            >> $CABALHOME/config
-    echo "symlink-bindir:    $CABALHOME/bin"            >> $CABALHOME/config
-    echo "installdir:        $CABALHOME/bin"            >> $CABALHOME/config
-    echo "build-summary:     $CABALHOME/logs/build.log" >> $CABALHOME/config
-    echo "store-dir:         $CABALHOME/store"          >> $CABALHOME/config
-    echo "install-dirs user"                            >> $CABALHOME/config
-    echo "  prefix: $CABALHOME"                         >> $CABALHOME/config
-    echo "repository hackage.haskell.org"               >> $CABALHOME/config
-    echo "  url: http://hackage.haskell.org/"           >> $CABALHOME/config
+    echo "verbose: normal +nowrap +markoutput"                                  >> $CABALHOME/config
+    echo "remote-build-reporting: anonymous"                                    >> $CABALHOME/config
+    echo "write-ghc-environment-files: always"                                  >> $CABALHOME/config
+    echo "remote-repo-cache: $CABALHOME/packages"                               >> $CABALHOME/config
+    echo "logs-dir:          $CABALHOME/logs"                                   >> $CABALHOME/config
+    echo "world-file:        $CABALHOME/world"                                  >> $CABALHOME/config
+    echo "extra-prog-path:   $CABALHOME/bin"                                    >> $CABALHOME/config
+    echo "symlink-bindir:    $CABALHOME/bin"                                    >> $CABALHOME/config
+    echo "installdir:        $CABALHOME/bin"                                    >> $CABALHOME/config
+    echo "build-summary:     $CABALHOME/logs/build.log"                         >> $CABALHOME/config
+    echo "store-dir:         $CABALHOME/store"                                  >> $CABALHOME/config
+    echo "install-dirs user"                                                    >> $CABALHOME/config
+    echo "  prefix: $CABALHOME"                                                 >> $CABALHOME/config
+    echo "repository hackage.haskell.org"                                       >> $CABALHOME/config
+    echo "  url: http://hackage.haskell.org/"                                   >> $CABALHOME/config
+    echo "  secure: True"                                                       >> $CABALHOME/config
+    echo "  key-threshold: 3"                                                   >> $CABALHOME/config
+    echo "  root-keys:"                                                         >> $CABALHOME/config
+    echo "    fe331502606802feac15e514d9b9ea83fee8b6ffef71335479a2e68d84adc6b0" >> $CABALHOME/config
+    echo "    1ea9ba32c526d1cc91ab5e5bd364ec5e9e8cb67179a471872f6e26f0ae773d42" >> $CABALHOME/config
+    echo "    2c6c3627bd6c982990239487f1abd02e08a02e6cf16edb105a8012d444d870c3" >> $CABALHOME/config
+    echo "    0a5c7ea47cd1b15f01f5f51a33adda7e655bc0f0b0615baa8e271f4c3351e21d" >> $CABALHOME/config
+    echo "    51f0161b906011b52c6613376b1ae937670da69322113a246a09f807c62f6921" >> $CABALHOME/config
+  - |
+    echo "program-default-options"                >> $CABALHOME/config
+    echo "  ghc-options: $GHCJOBS +RTS -M6G -RTS" >> $CABALHOME/config
   - cat $CABALHOME/config
   - rm -fv cabal.project cabal.project.local cabal.project.freeze
   - travis_retry ${CABAL} v2-update -v
@@ -97,6 +113,8 @@ install:
     echo "packages: ./subs/lambda-simple" >> cabal.project
     echo "packages: ./subs/lambda-untyped" >> cabal.project
     echo "packages: ./subs/lambda-fullsimple" >> cabal.project
+    echo "packages: ./subs/recon" >> cabal.project
+    echo "packages: ./subs/systemf" >> cabal.project
   - |
     echo "package tapl"              >> cabal.project
     echo "  ghc-options: -Werror"    >> cabal.project
@@ -121,7 +139,13 @@ install:
     echo ""                          >> cabal.project
     echo "package lambda-fullsimple" >> cabal.project
     echo "  ghc-options: -Werror"    >> cabal.project
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(arith|bool|haskeline|lambda-core|lambda-fullsimple|lambda-simple|lambda-untyped|tapl|term)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+    echo ""                          >> cabal.project
+    echo "package recon"             >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+    echo ""                          >> cabal.project
+    echo "package systemf"           >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(arith|bool|haskeline|lambda-core|lambda-fullsimple|lambda-simple|lambda-untyped|recon|systemf|tapl|term)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   - if [ -f "./configure.ac" ]; then (cd "." && autoreconf -i); fi
@@ -132,6 +156,8 @@ install:
   - if [ -f "./subs/lambda-simple/configure.ac" ]; then (cd "./subs/lambda-simple" && autoreconf -i); fi
   - if [ -f "./subs/lambda-untyped/configure.ac" ]; then (cd "./subs/lambda-untyped" && autoreconf -i); fi
   - if [ -f "./subs/lambda-fullsimple/configure.ac" ]; then (cd "./subs/lambda-fullsimple" && autoreconf -i); fi
+  - if [ -f "./subs/recon/configure.ac" ]; then (cd "./subs/recon" && autoreconf -i); fi
+  - if [ -f "./subs/systemf/configure.ac" ]; then (cd "./subs/systemf" && autoreconf -i); fi
   - ${CABAL} v2-freeze $WITHCOMPILER ${TEST} ${BENCH} | color_cabal_output
   - "cat cabal.project.freeze | sed -E 's/^(constraints: *| *)//' | sed 's/any.//'"
   - rm  cabal.project.freeze
@@ -154,6 +180,8 @@ script:
   - PKGDIR_lambda_simple="$(find . -maxdepth 1 -type d -regex '.*/lambda-simple-[0-9.]*')"
   - PKGDIR_lambda_untyped="$(find . -maxdepth 1 -type d -regex '.*/lambda-untyped-[0-9.]*')"
   - PKGDIR_lambda_fullsimple="$(find . -maxdepth 1 -type d -regex '.*/lambda-fullsimple-[0-9.]*')"
+  - PKGDIR_recon="$(find . -maxdepth 1 -type d -regex '.*/recon-[0-9.]*')"
+  - PKGDIR_systemf="$(find . -maxdepth 1 -type d -regex '.*/systemf-[0-9.]*')"
   # Generate cabal.project
   - rm -rf cabal.project cabal.project.local cabal.project.freeze
   - touch cabal.project
@@ -166,6 +194,8 @@ script:
     echo "packages: ${PKGDIR_lambda_simple}" >> cabal.project
     echo "packages: ${PKGDIR_lambda_untyped}" >> cabal.project
     echo "packages: ${PKGDIR_lambda_fullsimple}" >> cabal.project
+    echo "packages: ${PKGDIR_recon}" >> cabal.project
+    echo "packages: ${PKGDIR_systemf}" >> cabal.project
   - |
     echo "package tapl"              >> cabal.project
     echo "  ghc-options: -Werror"    >> cabal.project
@@ -190,7 +220,13 @@ script:
     echo ""                          >> cabal.project
     echo "package lambda-fullsimple" >> cabal.project
     echo "  ghc-options: -Werror"    >> cabal.project
-  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(arith|bool|haskeline|lambda-core|lambda-fullsimple|lambda-simple|lambda-untyped|tapl|term)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
+    echo ""                          >> cabal.project
+    echo "package recon"             >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+    echo ""                          >> cabal.project
+    echo "package systemf"           >> cabal.project
+    echo "  ghc-options: -Werror"    >> cabal.project
+  - "for pkg in $($HCPKG list --simple-output); do echo $pkg | sed 's/-[^-]*$//' | (grep -vE -- '^(arith|bool|haskeline|lambda-core|lambda-fullsimple|lambda-simple|lambda-untyped|recon|systemf|tapl|term)$' || true) | sed 's/^/constraints: /' | sed 's/$/ installed/' >> cabal.project.local; done"
   - cat cabal.project || true
   - cat cabal.project.local || true
   # Building...
@@ -203,7 +239,7 @@ script:
   # Testing...
   - ${CABAL} v2-test $WITHCOMPILER ${TEST} ${BENCH} all | color_cabal_output
   # haddock...
-  - ${CABAL} v2-haddock $WITHCOMPILER ${TEST} ${BENCH} all | color_cabal_output
+  - ${CABAL} v2-haddock $WITHCOMPILER --with-haddock $HADDOCK ${TEST} ${BENCH} all | color_cabal_output
 
-# REGENDATA ["--config","cabal.haskell-ci","cabal.project"]
+# REGENDATA ("0.8",["--config","cabal.haskell-ci","cabal.project"])
 # EOF
